export const ADD_AUTHOR_STARTED = 'ADD_AUTHOR_STARTED';
export const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS';
export const ADD_AUTHOR_FAILURE = 'ADD_AUTHOR_FAILURE';
export const GET_ALL_AUTHORS_STARTED = 'GET_ALL_AUTHORS_STARTED';
export const GET_ALL_AUTHORS_SUCCESS = 'GET_ALL_AUTHORS_SUCCESS';
export const GET_ALL_AUTHORS_FAILURE = 'GET_ALL_AUTHORS_FAILURE';
